//FILTERS
export const FILTERS_CHANGE_CITYNAME = 'FILTERS_CHANGE_CITYNAME';
export const FILTERS_CHANGE_SEX = 'FILTERS_CHANGE_SEX';
export const FILTERS_CHANGE_AGE = 'FILTERS_CHANGE_AGE';
export const FILTERS_CHANGE_PLACE = 'FILTERS_CHANGE_PLACE';
//TOP
export const TOP_UPDATE_USERSLIST = 'TOP_UPDATE_USERSLIST';
export const TOP_UPDATE_USERSLILST_INDICATOR_TOGGLE = 'TOP_UPDATE_USERSLILST_INDICATOR_TOGGLE';
export const TOP_UPDATE_USERSLILST_SEX = 'TOP_UPDATE_USERSLILST_SEX';
export const TOP_CLEAR_USERSLILST = 'TOP_CLEAR_USERSLILST';
//LIKES
export const LIKES_UPDATE_USERSLIST = 'LIKES_UPDATE_USERSLIST';
export const LIKES_UPDATE_USERSLILST_INDICATOR_TOGGLE = 'LIKES_UPDATE_USERSLILST_INDICATOR_TOGGLE';
export const LIKES_UPDATE_USERSLILST_SEX = 'LIKES_UPDATE_USERSLILST_SEX';
export const LIKES_CLEAR_USERSLILST = 'LIKES_CLEAR_USERSLILST';
//USER
export const USER_UPDATE_FIRSTNAME = 'USER_UPDATE_INFO';
export const USER_UPDATE_OWNLIKES = 'USER_UPDATE_OWNLIKES';
export const USER_UPDATE_USERSLIKES = 'USER_UPDATE_USERSLIKES';
export const USER_UPDATE_BATTLESCOUNT = 'USER_UPDATE_BATTLESCOUNT';
export const USER_UPDATE_NOTIFICATIONSENABLED = 'USER_UPDATE_NOTIFICATIONSENABLED';
export const USER_UPDATE_PHOTO_100 = 'USER_UPDATE_PHOTO_100';
export const USER_UPDATE_SEX = 'USER_UPDATE_SEX';
//QUESTS
export const QUESTS_UPDATE_CURRENT_REWARD = 'QUESTS_UPDATE_CURRENT_REWARD';
export const QUESTS_SET_GLOBAL_TIMER_ID = 'QUESTS_SET_GLOBAL_TIMER_ID';
//ONLINE
export const ONLINE_UPDATE = 'ONLINE_UPDATE';
